version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: nginx:latest
    ports:
      - "18151:18151"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
