version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web

  nginx:
    image: nginx:latest
    ports:
      - "18151:18151"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  bombardier:
    build:
      context: .
      dockerfile: Dockerfile.bombardier
  
    depends_on:
      - nginx
