services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      sqlserver:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "18151:18151"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:18151/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  bombardier:
    build:
      context: .
      dockerfile: Dockerfile.bombardier
    depends_on:
      - nginx

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    volumes:
      - ./sqlserver-init:/docker-entrypoint-initdb.d
    environment:
      SA_PASSWORD: "YourStrongPassw0rd"
      ACCEPT_EULA: "Y"
    healthcheck:
      # test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -b -C -S sqlserver -U sa -P YourStrongPassw0rd -d master -Q 'SELECT 1'"]
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -b -C -S sqlserver -U sa -P YourStrongPassw0rd -d master -i /docker-entrypoint-initdb.d/000-initialschema.sql"]
      interval: 10s
      timeout: 30s
      retries: 30
