name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build

  test:
    runs-on: ubuntu-latest
    name: Run very-bad-sync-slow tests

    needs: build

    env:
      ROUTE_NAME: "very-bad-sync-slow"

    steps:
    - uses: actions/checkout@v4
    - name: Create logs directory
      run: mkdir -p logs
    - name: Runs the Docker image
      run: docker compose up -d
    - name: Run a moderate load test
      run: docker exec dotnet-nginx-testing-bombardier-1 /bombardier-scripts/run-tests.sh --route-name $ROUTE_NAME > logs/bombardier-container.log
    - name: Capture logs
      run: docker logs dotnet-nginx-testing-web-1 > logs/web-container.log
    - name: Capture Nginx logs
      run: docker logs dotnet-nginx-testing-nginx-1 > logs/nginx-container.log
    - name: Capture Bombardier logs
      run: docker logs dotnet-nginx-testing-bombardier-1 > logs/bombardier-container.log
    - name: Upload logs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-container-logs
        path: logs/*.log
    - name: Stop the Docker image
      run: docker compose down
