name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build
    - name: Runs the Docker image
      run: docker compose up -d
    - name: Run a moderate load test
      run: docker exec dotnet-nginx-testing-bombardier-1 /bombardier-scripts/run-tests.sh
    - name: Stop the Docker image
      run: docker compose down
